//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGenealogy.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGenealogy.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MsgBox_Button_No {
            get {
                return ResourceManager.GetString("MsgBox_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No and Don&apos;t Ask Again.
        /// </summary>
        internal static string MsgBox_Button_NoNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_NoNoAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MsgBox_Button_Yes {
            get {
                return ResourceManager.GetString("MsgBox_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes and Don&apos;t Ask Again.
        /// </summary>
        internal static string MsgBox_Button_YesNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_YesNoAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string MsgBox_Title_Failure {
            get {
                return ResourceManager.GetString("MsgBox_Title_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string MsgBox_Title_Notice {
            get {
                return ResourceManager.GetString("MsgBox_Title_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MsgBox_Title_Success {
            get {
                return ResourceManager.GetString("MsgBox_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MsgBox_Title_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back up the current file.
        /// </summary>
        internal static string XAML_FilePage_BackupFile_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_BackupFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string XAML_FilePage_BackupFile_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_BackupFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the current file.
        /// </summary>
        internal static string XAML_FilePage_CloseFile_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_CloseFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        internal static string XAML_FilePage_CloseFile_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_CloseFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Smart Genealogy file.
        /// </summary>
        internal static string XAML_FilePage_CreateFile_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_CreateFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create File.
        /// </summary>
        internal static string XAML_FilePage_CreateFile_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_CreateFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current File:.
        /// </summary>
        internal static string XAML_FilePage_CurrentFile {
            get {
                return ResourceManager.GetString("XAML_FilePage_CurrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports data from the current file.
        /// </summary>
        internal static string XAML_FilePage_ExportData_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_ExportData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        internal static string XAML_FilePage_ExportData_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_ExportData_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports data into the current file.
        /// </summary>
        internal static string XAML_FilePage_ImportData_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_ImportData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        internal static string XAML_FilePage_ImportData_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_ImportData_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing Smart Genealogy file.
        /// </summary>
        internal static string XAML_FilePage_OpenFile_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_OpenFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string XAML_FilePage_OpenFile_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_OpenFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore an existing backup of a Smart Genealogy file.
        /// </summary>
        internal static string XAML_FilePage_RestoreFile_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_RestoreFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore File.
        /// </summary>
        internal static string XAML_FilePage_RestoreFile_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_RestoreFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tools on the current file.
        /// </summary>
        internal static string XAML_FilePage_Tools_Description {
            get {
                return ResourceManager.GetString("XAML_FilePage_Tools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string XAML_FilePage_Tools_Header {
            get {
                return ResourceManager.GetString("XAML_FilePage_Tools_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string XAML_Navigation_Addresses {
            get {
                return ResourceManager.GetString("XAML_Navigation_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string XAML_Navigation_File {
            get {
                return ResourceManager.GetString("XAML_Navigation_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string XAML_Navigation_Home {
            get {
                return ResourceManager.GetString("XAML_Navigation_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string XAML_Navigation_Media {
            get {
                return ResourceManager.GetString("XAML_Navigation_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string XAML_Navigation_People {
            get {
                return ResourceManager.GetString("XAML_Navigation_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        internal static string XAML_Navigation_Places {
            get {
                return ResourceManager.GetString("XAML_Navigation_Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string XAML_Navigation_Publish {
            get {
                return ResourceManager.GetString("XAML_Navigation_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string XAML_Navigation_Search {
            get {
                return ResourceManager.GetString("XAML_Navigation_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string XAML_Navigation_Settings {
            get {
                return ResourceManager.GetString("XAML_Navigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string XAML_Navigation_Sources {
            get {
                return ResourceManager.GetString("XAML_Navigation_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string XAML_Navigation_Tasks {
            get {
                return ResourceManager.GetString("XAML_Navigation_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string XAML_Navigation_Tools {
            get {
                return ResourceManager.GetString("XAML_Navigation_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current app theme.
        /// </summary>
        internal static string XAML_SettingsPage_AppTheme_Description {
            get {
                return ResourceManager.GetString("XAML_SettingsPage_AppTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        internal static string XAML_SettingsPage_AppTheme_Header {
            get {
                return ResourceManager.GetString("XAML_SettingsPage_AppTheme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current language.
        /// </summary>
        internal static string XAML_SettingsPage_Language_Description {
            get {
                return ResourceManager.GetString("XAML_SettingsPage_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string XAML_SettingsPage_Language_Header {
            get {
                return ResourceManager.GetString("XAML_SettingsPage_Language_Header", resourceCulture);
            }
        }
    }
}
