//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGenealogy.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGenealogy.Resources.Translations.AppTranslations", typeof(AppTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model.
        /// </summary>
        internal static string ButtonChooseModel {
            get {
                return ResourceManager.GetString("ButtonChooseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        internal static string ButtonContactUs {
            get {
                return ResourceManager.GetString("ButtonContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string ButtonDarkTheme {
            get {
                return ResourceManager.GetString("ButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string ButtonLightTheme {
            get {
                return ResourceManager.GetString("ButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test App.
        /// </summary>
        internal static string LabelApp {
            get {
                return ResourceManager.GetString("LabelApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test app description.
        /// </summary>
        internal static string LabelAppDescription {
            get {
                return ResourceManager.GetString("LabelAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Theme.
        /// </summary>
        internal static string LabelChooseTheme {
            get {
                return ResourceManager.GetString("LabelChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string LabelFiles {
            get {
                return ResourceManager.GetString("LabelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Path.
        /// </summary>
        internal static string LabelModelPath {
            get {
                return ResourceManager.GetString("LabelModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Smart Genealogy file.
        /// </summary>
        internal static string LabelNewFile {
            get {
                return ResourceManager.GetString("LabelNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Smart Genealogy database file.
        /// </summary>
        internal static string LabelNewFileDescription {
            get {
                return ResourceManager.GetString("LabelNewFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Smart Genealogy file.
        /// </summary>
        internal static string LabelOpenFile {
            get {
                return ResourceManager.GetString("LabelOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing Smart Genealogy database file.
        /// </summary>
        internal static string LabelOpenFileDescription {
            get {
                return ResourceManager.GetString("LabelOpenFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your Color.
        /// </summary>
        internal static string LabelPickColor {
            get {
                return ResourceManager.GetString("LabelPickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore from Backup.
        /// </summary>
        internal static string LabelRestoreFile {
            get {
                return ResourceManager.GetString("LabelRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a Smart Genealogy file from backup.
        /// </summary>
        internal static string LabelRestoreFileDescription {
            get {
                return ResourceManager.GetString("LabelRestoreFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string MenuMainAbout {
            get {
                return ResourceManager.GetString("MenuMainAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string MenuMainAddresses {
            get {
                return ResourceManager.GetString("MenuMainAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string MenuMainChat {
            get {
                return ResourceManager.GetString("MenuMainChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuMainFile {
            get {
                return ResourceManager.GetString("MenuMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuMainHome {
            get {
                return ResourceManager.GetString("MenuMainHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string MenuMainMedia {
            get {
                return ResourceManager.GetString("MenuMainMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string MenuMainPeople {
            get {
                return ResourceManager.GetString("MenuMainPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        internal static string MenuMainPlaces {
            get {
                return ResourceManager.GetString("MenuMainPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string MenuMainPublish {
            get {
                return ResourceManager.GetString("MenuMainPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MenuMainSearch {
            get {
                return ResourceManager.GetString("MenuMainSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuMainSettings {
            get {
                return ResourceManager.GetString("MenuMainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string MenuMainSources {
            get {
                return ResourceManager.GetString("MenuMainSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string MenuMainTasks {
            get {
                return ResourceManager.GetString("MenuMainTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MenuMainTools {
            get {
                return ResourceManager.GetString("MenuMainTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string PageTitleAboutUs {
            get {
                return ResourceManager.GetString("PageTitleAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string StringAboutUs {
            get {
                return ResourceManager.GetString("StringAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Genealogy.
        /// </summary>
        internal static string StringCopyright {
            get {
                return ResourceManager.GetString("StringCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message....
        /// </summary>
        internal static string StringEnterMessage {
            get {
                return ResourceManager.GetString("StringEnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Smart Genealogy.
        /// </summary>
        internal static string StringWelcomeToSmartGenealogy {
            get {
                return ResourceManager.GetString("StringWelcomeToSmartGenealogy", resourceCulture);
            }
        }
    }
}
